FROM golang:alpine as builder   

RUN mkdir /build

ADD . /build/

WORKDIR /build

RUN go build -o main .

FROM alpine 

RUN adduser -S -D -H -h /app appuser 

COPY . /app

COPY --from=builder /build/main /app/builder

WORKDIR /app 

EXPOSE 3000

CMD ["./main"]